-- Script Date: 12-Nov-18 11:31 PM  - ErikEJ.SqlCeScripting version 3.5.2.75
DROP TABLE [CASES];
CREATE TABLE [CASES] (
  [CASE_ID] INTEGER  NOT NULL
, [STATUS ] text NOT NULL
, [HOURS_BILLED] bigint  NOT NULL
, [CL_ID] bigint  NOT NULL
, [STAGE] text NOT NULL
, [COURTROOM_NO] text NOT NULL
, [NAME] text DEFAULT ' ' NULL
, CONSTRAINT [sqlite_master_PK_CASES] PRIMARY KEY ([CASE_ID])
, CONSTRAINT [FK_CASES] FOREIGN KEY ([CL_ID]) REFERENCES [CLIENT]([CL_ID])
);
