-- Script Date: 09-Nov-18 11:17 PM  - ErikEJ.SqlCeScripting version 3.5.2.75
CREATE TABLE [COUNSELS] (
  [CL_ID] INTEGER NOT NULL
, [L_ID] INTEGER NOT NULL
, CONSTRAINT [PK_COUNSELS] PRIMARY KEY ([CL_ID],[L_ID])
, CONSTRAINT [FK_COUNSELS] FOREIGN KEY ([CL_ID]) REFERENCES [CLIENT]([CL_ID])
, CONSTRAINT [FK_COUNSELS] FOREIGN KEY ([L_ID]) REFERENCES [LAWYER]([L_ID])
);
