-- Script Date: 09-Nov-18 11:39 PM  - ErikEJ.SqlCeScripting version 3.5.2.75
CREATE TABLE [HANDLES] (
  [L_ID] INTEGER NOT NULL
, [CASE_ID] INTEGER NOT NULL
, CONSTRAINT [PK_HANDLES] PRIMARY KEY ([L_ID],[CASE_ID])
, CONSTRAINT [FK_HANDLES] FOREIGN KEY ([L_ID]) REFERENCES [LAWYER]([L_ID])
, CONSTRAINT [FK_HANDLES] FOREIGN KEY ([CASE_ID]) REFERENCES [CASES]([CASE_ID])
);
