-- Script Date: 16-Nov-18 11:14 AM  - ErikEJ.SqlCeScripting version 3.5.2.75
CREATE TABLE [LAWYER] (
  [L_ID] INTEGER NOT NULL
, [NAME] TEXT NOT NULL
, [DESIGNATION] TEXT NOT NULL
, [BILLABLES] INTEGER NOT NULL
, [PHONE] TEXT NOT NULL
, [PASSWORD] TEXT NOT NULL
, CONSTRAINT [PK_LAWYER] PRIMARY KEY ([L_ID])
);
