-- Script Date: 09-Nov-18 10:59 PM  - ErikEJ.SqlCeScripting version 3.5.2.75
CREATE TABLE [PARALEGALS] (
  [P_ID] INTEGER NOT NULL
, [PHONE] TEXT NOT NULL
, CONSTRAINT [PK_PARALEGALS] PRIMARY KEY ([P_ID])
);
